image: luomingxu/docker:stable

variables:
  Cache_Location: /cache/$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
  Image_Name: "bilibili-spider"

stages:
  - docker_build
  - deploy

docker:
  stage: docker_build
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
  before_script:
    - mkdir -p ~/.ssh
    - cp $SSH_KEY ~/.ssh/id_ed25519
    - chmod 400 ~/.ssh/id_ed25519
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git config --global user.name "$GitUserName"
    - git config --global user.email "$GitUserEmail"
  script:
    - git submodule update --init --recursive config
    - mkdir -p $Cache_Location
    - cp -r ./* $Cache_Location/
    - cd $Cache_Location/
    - image=$(echo $Image_Name:$CI_COMMIT_SHORT_SHA|tr [:upper:] [:lower:])
    - docker build -t $image .
    - docker tag $image $Image_Name:latest
  tags:
    - docker-executor

deploy:
  image:
    name: docker/compose:latest
    entrypoint: ["/bin/sh", "-c"]
  when: on_success
  stage: deploy
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - docker-compose version
    - docker-compose up -d
  tags:
    - docker-executor
