// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serialize.proto

package bilibilispider.multiprocess;

public final class Serialize {
  private Serialize() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bilibilispider.multiprocess.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    java.util.List<bilibilispider.multiprocess.Serialize.Msg.DanmakuP> 
        getDanmakusList();
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    bilibilispider.multiprocess.Serialize.Msg.DanmakuP getDanmakus(int index);
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    int getDanmakusCount();
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    java.util.List<? extends bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder> 
        getDanmakusOrBuilderList();
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder getDanmakusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bilibilispider.multiprocess.Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bilibilispider.multiprocess.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      danmakus_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                danmakus_ = new java.util.ArrayList<bilibilispider.multiprocess.Serialize.Msg.DanmakuP>();
                mutable_bitField0_ |= 0x00000001;
              }
              danmakus_.add(
                  input.readMessage(bilibilispider.multiprocess.Serialize.Msg.DanmakuP.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          danmakus_ = java.util.Collections.unmodifiableList(danmakus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bilibilispider.multiprocess.Serialize.Msg.class, bilibilispider.multiprocess.Serialize.Msg.Builder.class);
    }

    public interface DanmakuPOrBuilder extends
        // @@protoc_insertion_point(interface_extends:bilibilispider.multiprocess.Msg.DanmakuP)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      long getId();

      /**
       * <code>int32 mode = 2;</code>
       * @return The mode.
       */
      int getMode();

      /**
       * <code>int32 fontSize = 3;</code>
       * @return The fontSize.
       */
      int getFontSize();

      /**
       * <code>int32 fontColor = 4;</code>
       * @return The fontColor.
       */
      int getFontColor();

      /**
       * <code>int64 sendTime = 5;</code>
       * @return The sendTime.
       */
      long getSendTime();

      /**
       * <code>int32 danmakuPool = 6;</code>
       * @return The danmakuPool.
       */
      int getDanmakuPool();

      /**
       * <code>double danmakuEpoch = 8;</code>
       * @return The danmakuEpoch.
       */
      double getDanmakuEpoch();

      /**
       * <code>int64 userHash = 9;</code>
       * @return The userHash.
       */
      long getUserHash();

      /**
       * <code>int64 userId = 10;</code>
       * @return The userId.
       */
      long getUserId();

      /**
       * <code>string content = 11;</code>
       * @return The content.
       */
      java.lang.String getContent();
      /**
       * <code>string content = 11;</code>
       * @return The bytes for content.
       */
      com.google.protobuf.ByteString
          getContentBytes();
    }
    /**
     * Protobuf type {@code bilibilispider.multiprocess.Msg.DanmakuP}
     */
    public  static final class DanmakuP extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:bilibilispider.multiprocess.Msg.DanmakuP)
        DanmakuPOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DanmakuP.newBuilder() to construct.
      private DanmakuP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DanmakuP() {
        content_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new DanmakuP();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DanmakuP(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt64();
                break;
              }
              case 16: {

                mode_ = input.readInt32();
                break;
              }
              case 24: {

                fontSize_ = input.readInt32();
                break;
              }
              case 32: {

                fontColor_ = input.readInt32();
                break;
              }
              case 40: {

                sendTime_ = input.readInt64();
                break;
              }
              case 48: {

                danmakuPool_ = input.readInt32();
                break;
              }
              case 65: {

                danmakuEpoch_ = input.readDouble();
                break;
              }
              case 72: {

                userHash_ = input.readInt64();
                break;
              }
              case 80: {

                userId_ = input.readInt64();
                break;
              }
              case 90: {
                java.lang.String s = input.readStringRequireUtf8();

                content_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_DanmakuP_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_DanmakuP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibilispider.multiprocess.Serialize.Msg.DanmakuP.class, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }

      public static final int MODE_FIELD_NUMBER = 2;
      private int mode_;
      /**
       * <code>int32 mode = 2;</code>
       * @return The mode.
       */
      public int getMode() {
        return mode_;
      }

      public static final int FONTSIZE_FIELD_NUMBER = 3;
      private int fontSize_;
      /**
       * <code>int32 fontSize = 3;</code>
       * @return The fontSize.
       */
      public int getFontSize() {
        return fontSize_;
      }

      public static final int FONTCOLOR_FIELD_NUMBER = 4;
      private int fontColor_;
      /**
       * <code>int32 fontColor = 4;</code>
       * @return The fontColor.
       */
      public int getFontColor() {
        return fontColor_;
      }

      public static final int SENDTIME_FIELD_NUMBER = 5;
      private long sendTime_;
      /**
       * <code>int64 sendTime = 5;</code>
       * @return The sendTime.
       */
      public long getSendTime() {
        return sendTime_;
      }

      public static final int DANMAKUPOOL_FIELD_NUMBER = 6;
      private int danmakuPool_;
      /**
       * <code>int32 danmakuPool = 6;</code>
       * @return The danmakuPool.
       */
      public int getDanmakuPool() {
        return danmakuPool_;
      }

      public static final int DANMAKUEPOCH_FIELD_NUMBER = 8;
      private double danmakuEpoch_;
      /**
       * <code>double danmakuEpoch = 8;</code>
       * @return The danmakuEpoch.
       */
      public double getDanmakuEpoch() {
        return danmakuEpoch_;
      }

      public static final int USERHASH_FIELD_NUMBER = 9;
      private long userHash_;
      /**
       * <code>int64 userHash = 9;</code>
       * @return The userHash.
       */
      public long getUserHash() {
        return userHash_;
      }

      public static final int USERID_FIELD_NUMBER = 10;
      private long userId_;
      /**
       * <code>int64 userId = 10;</code>
       * @return The userId.
       */
      public long getUserId() {
        return userId_;
      }

      public static final int CONTENT_FIELD_NUMBER = 11;
      private volatile java.lang.Object content_;
      /**
       * <code>string content = 11;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        }
      }
      /**
       * <code>string content = 11;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0L) {
          output.writeInt64(1, id_);
        }
        if (mode_ != 0) {
          output.writeInt32(2, mode_);
        }
        if (fontSize_ != 0) {
          output.writeInt32(3, fontSize_);
        }
        if (fontColor_ != 0) {
          output.writeInt32(4, fontColor_);
        }
        if (sendTime_ != 0L) {
          output.writeInt64(5, sendTime_);
        }
        if (danmakuPool_ != 0) {
          output.writeInt32(6, danmakuPool_);
        }
        if (danmakuEpoch_ != 0D) {
          output.writeDouble(8, danmakuEpoch_);
        }
        if (userHash_ != 0L) {
          output.writeInt64(9, userHash_);
        }
        if (userId_ != 0L) {
          output.writeInt64(10, userId_);
        }
        if (!getContentBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 11, content_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, id_);
        }
        if (mode_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, mode_);
        }
        if (fontSize_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, fontSize_);
        }
        if (fontColor_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, fontColor_);
        }
        if (sendTime_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, sendTime_);
        }
        if (danmakuPool_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, danmakuPool_);
        }
        if (danmakuEpoch_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(8, danmakuEpoch_);
        }
        if (userHash_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(9, userHash_);
        }
        if (userId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(10, userId_);
        }
        if (!getContentBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, content_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof bilibilispider.multiprocess.Serialize.Msg.DanmakuP)) {
          return super.equals(obj);
        }
        bilibilispider.multiprocess.Serialize.Msg.DanmakuP other = (bilibilispider.multiprocess.Serialize.Msg.DanmakuP) obj;

        if (getId()
            != other.getId()) return false;
        if (getMode()
            != other.getMode()) return false;
        if (getFontSize()
            != other.getFontSize()) return false;
        if (getFontColor()
            != other.getFontColor()) return false;
        if (getSendTime()
            != other.getSendTime()) return false;
        if (getDanmakuPool()
            != other.getDanmakuPool()) return false;
        if (java.lang.Double.doubleToLongBits(getDanmakuEpoch())
            != java.lang.Double.doubleToLongBits(
                other.getDanmakuEpoch())) return false;
        if (getUserHash()
            != other.getUserHash()) return false;
        if (getUserId()
            != other.getUserId()) return false;
        if (!getContent()
            .equals(other.getContent())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
        hash = (37 * hash) + MODE_FIELD_NUMBER;
        hash = (53 * hash) + getMode();
        hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getFontSize();
        hash = (37 * hash) + FONTCOLOR_FIELD_NUMBER;
        hash = (53 * hash) + getFontColor();
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSendTime());
        hash = (37 * hash) + DANMAKUPOOL_FIELD_NUMBER;
        hash = (53 * hash) + getDanmakuPool();
        hash = (37 * hash) + DANMAKUEPOCH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDanmakuEpoch()));
        hash = (37 * hash) + USERHASH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserHash());
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(bilibilispider.multiprocess.Serialize.Msg.DanmakuP prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code bilibilispider.multiprocess.Msg.DanmakuP}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:bilibilispider.multiprocess.Msg.DanmakuP)
          bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_DanmakuP_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_DanmakuP_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  bilibilispider.multiprocess.Serialize.Msg.DanmakuP.class, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder.class);
        }

        // Construct using bilibilispider.multiprocess.Serialize.Msg.DanmakuP.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0L;

          mode_ = 0;

          fontSize_ = 0;

          fontColor_ = 0;

          sendTime_ = 0L;

          danmakuPool_ = 0;

          danmakuEpoch_ = 0D;

          userHash_ = 0L;

          userId_ = 0L;

          content_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_DanmakuP_descriptor;
        }

        @java.lang.Override
        public bilibilispider.multiprocess.Serialize.Msg.DanmakuP getDefaultInstanceForType() {
          return bilibilispider.multiprocess.Serialize.Msg.DanmakuP.getDefaultInstance();
        }

        @java.lang.Override
        public bilibilispider.multiprocess.Serialize.Msg.DanmakuP build() {
          bilibilispider.multiprocess.Serialize.Msg.DanmakuP result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public bilibilispider.multiprocess.Serialize.Msg.DanmakuP buildPartial() {
          bilibilispider.multiprocess.Serialize.Msg.DanmakuP result = new bilibilispider.multiprocess.Serialize.Msg.DanmakuP(this);
          result.id_ = id_;
          result.mode_ = mode_;
          result.fontSize_ = fontSize_;
          result.fontColor_ = fontColor_;
          result.sendTime_ = sendTime_;
          result.danmakuPool_ = danmakuPool_;
          result.danmakuEpoch_ = danmakuEpoch_;
          result.userHash_ = userHash_;
          result.userId_ = userId_;
          result.content_ = content_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof bilibilispider.multiprocess.Serialize.Msg.DanmakuP) {
            return mergeFrom((bilibilispider.multiprocess.Serialize.Msg.DanmakuP)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(bilibilispider.multiprocess.Serialize.Msg.DanmakuP other) {
          if (other == bilibilispider.multiprocess.Serialize.Msg.DanmakuP.getDefaultInstance()) return this;
          if (other.getId() != 0L) {
            setId(other.getId());
          }
          if (other.getMode() != 0) {
            setMode(other.getMode());
          }
          if (other.getFontSize() != 0) {
            setFontSize(other.getFontSize());
          }
          if (other.getFontColor() != 0) {
            setFontColor(other.getFontColor());
          }
          if (other.getSendTime() != 0L) {
            setSendTime(other.getSendTime());
          }
          if (other.getDanmakuPool() != 0) {
            setDanmakuPool(other.getDanmakuPool());
          }
          if (other.getDanmakuEpoch() != 0D) {
            setDanmakuEpoch(other.getDanmakuEpoch());
          }
          if (other.getUserHash() != 0L) {
            setUserHash(other.getUserHash());
          }
          if (other.getUserId() != 0L) {
            setUserId(other.getUserId());
          }
          if (!other.getContent().isEmpty()) {
            content_ = other.content_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          bilibilispider.multiprocess.Serialize.Msg.DanmakuP parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (bilibilispider.multiprocess.Serialize.Msg.DanmakuP) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long id_ ;
        /**
         * <code>int64 id = 1;</code>
         * @return The id.
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>int64 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(long value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = 0L;
          onChanged();
          return this;
        }

        private int mode_ ;
        /**
         * <code>int32 mode = 2;</code>
         * @return The mode.
         */
        public int getMode() {
          return mode_;
        }
        /**
         * <code>int32 mode = 2;</code>
         * @param value The mode to set.
         * @return This builder for chaining.
         */
        public Builder setMode(int value) {
          
          mode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 mode = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearMode() {
          
          mode_ = 0;
          onChanged();
          return this;
        }

        private int fontSize_ ;
        /**
         * <code>int32 fontSize = 3;</code>
         * @return The fontSize.
         */
        public int getFontSize() {
          return fontSize_;
        }
        /**
         * <code>int32 fontSize = 3;</code>
         * @param value The fontSize to set.
         * @return This builder for chaining.
         */
        public Builder setFontSize(int value) {
          
          fontSize_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 fontSize = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearFontSize() {
          
          fontSize_ = 0;
          onChanged();
          return this;
        }

        private int fontColor_ ;
        /**
         * <code>int32 fontColor = 4;</code>
         * @return The fontColor.
         */
        public int getFontColor() {
          return fontColor_;
        }
        /**
         * <code>int32 fontColor = 4;</code>
         * @param value The fontColor to set.
         * @return This builder for chaining.
         */
        public Builder setFontColor(int value) {
          
          fontColor_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 fontColor = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearFontColor() {
          
          fontColor_ = 0;
          onChanged();
          return this;
        }

        private long sendTime_ ;
        /**
         * <code>int64 sendTime = 5;</code>
         * @return The sendTime.
         */
        public long getSendTime() {
          return sendTime_;
        }
        /**
         * <code>int64 sendTime = 5;</code>
         * @param value The sendTime to set.
         * @return This builder for chaining.
         */
        public Builder setSendTime(long value) {
          
          sendTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 sendTime = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearSendTime() {
          
          sendTime_ = 0L;
          onChanged();
          return this;
        }

        private int danmakuPool_ ;
        /**
         * <code>int32 danmakuPool = 6;</code>
         * @return The danmakuPool.
         */
        public int getDanmakuPool() {
          return danmakuPool_;
        }
        /**
         * <code>int32 danmakuPool = 6;</code>
         * @param value The danmakuPool to set.
         * @return This builder for chaining.
         */
        public Builder setDanmakuPool(int value) {
          
          danmakuPool_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 danmakuPool = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearDanmakuPool() {
          
          danmakuPool_ = 0;
          onChanged();
          return this;
        }

        private double danmakuEpoch_ ;
        /**
         * <code>double danmakuEpoch = 8;</code>
         * @return The danmakuEpoch.
         */
        public double getDanmakuEpoch() {
          return danmakuEpoch_;
        }
        /**
         * <code>double danmakuEpoch = 8;</code>
         * @param value The danmakuEpoch to set.
         * @return This builder for chaining.
         */
        public Builder setDanmakuEpoch(double value) {
          
          danmakuEpoch_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double danmakuEpoch = 8;</code>
         * @return This builder for chaining.
         */
        public Builder clearDanmakuEpoch() {
          
          danmakuEpoch_ = 0D;
          onChanged();
          return this;
        }

        private long userHash_ ;
        /**
         * <code>int64 userHash = 9;</code>
         * @return The userHash.
         */
        public long getUserHash() {
          return userHash_;
        }
        /**
         * <code>int64 userHash = 9;</code>
         * @param value The userHash to set.
         * @return This builder for chaining.
         */
        public Builder setUserHash(long value) {
          
          userHash_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 userHash = 9;</code>
         * @return This builder for chaining.
         */
        public Builder clearUserHash() {
          
          userHash_ = 0L;
          onChanged();
          return this;
        }

        private long userId_ ;
        /**
         * <code>int64 userId = 10;</code>
         * @return The userId.
         */
        public long getUserId() {
          return userId_;
        }
        /**
         * <code>int64 userId = 10;</code>
         * @param value The userId to set.
         * @return This builder for chaining.
         */
        public Builder setUserId(long value) {
          
          userId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 userId = 10;</code>
         * @return This builder for chaining.
         */
        public Builder clearUserId() {
          
          userId_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object content_ = "";
        /**
         * <code>string content = 11;</code>
         * @return The content.
         */
        public java.lang.String getContent() {
          java.lang.Object ref = content_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            content_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string content = 11;</code>
         * @return The bytes for content.
         */
        public com.google.protobuf.ByteString
            getContentBytes() {
          java.lang.Object ref = content_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            content_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string content = 11;</code>
         * @param value The content to set.
         * @return This builder for chaining.
         */
        public Builder setContent(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          content_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string content = 11;</code>
         * @return This builder for chaining.
         */
        public Builder clearContent() {
          
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        /**
         * <code>string content = 11;</code>
         * @param value The bytes for content to set.
         * @return This builder for chaining.
         */
        public Builder setContentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          content_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:bilibilispider.multiprocess.Msg.DanmakuP)
      }

      // @@protoc_insertion_point(class_scope:bilibilispider.multiprocess.Msg.DanmakuP)
      private static final bilibilispider.multiprocess.Serialize.Msg.DanmakuP DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new bilibilispider.multiprocess.Serialize.Msg.DanmakuP();
      }

      public static bilibilispider.multiprocess.Serialize.Msg.DanmakuP getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DanmakuP>
          PARSER = new com.google.protobuf.AbstractParser<DanmakuP>() {
        @java.lang.Override
        public DanmakuP parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DanmakuP(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DanmakuP> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DanmakuP> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public bilibilispider.multiprocess.Serialize.Msg.DanmakuP getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DANMAKUS_FIELD_NUMBER = 1;
    private java.util.List<bilibilispider.multiprocess.Serialize.Msg.DanmakuP> danmakus_;
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    public java.util.List<bilibilispider.multiprocess.Serialize.Msg.DanmakuP> getDanmakusList() {
      return danmakus_;
    }
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    public java.util.List<? extends bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder> 
        getDanmakusOrBuilderList() {
      return danmakus_;
    }
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    public int getDanmakusCount() {
      return danmakus_.size();
    }
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    public bilibilispider.multiprocess.Serialize.Msg.DanmakuP getDanmakus(int index) {
      return danmakus_.get(index);
    }
    /**
     * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
     */
    public bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder getDanmakusOrBuilder(
        int index) {
      return danmakus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < danmakus_.size(); i++) {
        output.writeMessage(1, danmakus_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < danmakus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, danmakus_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bilibilispider.multiprocess.Serialize.Msg)) {
        return super.equals(obj);
      }
      bilibilispider.multiprocess.Serialize.Msg other = (bilibilispider.multiprocess.Serialize.Msg) obj;

      if (!getDanmakusList()
          .equals(other.getDanmakusList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDanmakusCount() > 0) {
        hash = (37 * hash) + DANMAKUS_FIELD_NUMBER;
        hash = (53 * hash) + getDanmakusList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bilibilispider.multiprocess.Serialize.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bilibilispider.multiprocess.Serialize.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bilibilispider.multiprocess.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bilibilispider.multiprocess.Msg)
        bilibilispider.multiprocess.Serialize.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bilibilispider.multiprocess.Serialize.Msg.class, bilibilispider.multiprocess.Serialize.Msg.Builder.class);
      }

      // Construct using bilibilispider.multiprocess.Serialize.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDanmakusFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (danmakusBuilder_ == null) {
          danmakus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          danmakusBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bilibilispider.multiprocess.Serialize.internal_static_bilibilispider_multiprocess_Msg_descriptor;
      }

      @java.lang.Override
      public bilibilispider.multiprocess.Serialize.Msg getDefaultInstanceForType() {
        return bilibilispider.multiprocess.Serialize.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public bilibilispider.multiprocess.Serialize.Msg build() {
        bilibilispider.multiprocess.Serialize.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bilibilispider.multiprocess.Serialize.Msg buildPartial() {
        bilibilispider.multiprocess.Serialize.Msg result = new bilibilispider.multiprocess.Serialize.Msg(this);
        int from_bitField0_ = bitField0_;
        if (danmakusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            danmakus_ = java.util.Collections.unmodifiableList(danmakus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.danmakus_ = danmakus_;
        } else {
          result.danmakus_ = danmakusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bilibilispider.multiprocess.Serialize.Msg) {
          return mergeFrom((bilibilispider.multiprocess.Serialize.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bilibilispider.multiprocess.Serialize.Msg other) {
        if (other == bilibilispider.multiprocess.Serialize.Msg.getDefaultInstance()) return this;
        if (danmakusBuilder_ == null) {
          if (!other.danmakus_.isEmpty()) {
            if (danmakus_.isEmpty()) {
              danmakus_ = other.danmakus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDanmakusIsMutable();
              danmakus_.addAll(other.danmakus_);
            }
            onChanged();
          }
        } else {
          if (!other.danmakus_.isEmpty()) {
            if (danmakusBuilder_.isEmpty()) {
              danmakusBuilder_.dispose();
              danmakusBuilder_ = null;
              danmakus_ = other.danmakus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              danmakusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDanmakusFieldBuilder() : null;
            } else {
              danmakusBuilder_.addAllMessages(other.danmakus_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bilibilispider.multiprocess.Serialize.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bilibilispider.multiprocess.Serialize.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<bilibilispider.multiprocess.Serialize.Msg.DanmakuP> danmakus_ =
        java.util.Collections.emptyList();
      private void ensureDanmakusIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          danmakus_ = new java.util.ArrayList<bilibilispider.multiprocess.Serialize.Msg.DanmakuP>(danmakus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          bilibilispider.multiprocess.Serialize.Msg.DanmakuP, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder, bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder> danmakusBuilder_;

      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public java.util.List<bilibilispider.multiprocess.Serialize.Msg.DanmakuP> getDanmakusList() {
        if (danmakusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(danmakus_);
        } else {
          return danmakusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public int getDanmakusCount() {
        if (danmakusBuilder_ == null) {
          return danmakus_.size();
        } else {
          return danmakusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public bilibilispider.multiprocess.Serialize.Msg.DanmakuP getDanmakus(int index) {
        if (danmakusBuilder_ == null) {
          return danmakus_.get(index);
        } else {
          return danmakusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder setDanmakus(
          int index, bilibilispider.multiprocess.Serialize.Msg.DanmakuP value) {
        if (danmakusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDanmakusIsMutable();
          danmakus_.set(index, value);
          onChanged();
        } else {
          danmakusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder setDanmakus(
          int index, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder builderForValue) {
        if (danmakusBuilder_ == null) {
          ensureDanmakusIsMutable();
          danmakus_.set(index, builderForValue.build());
          onChanged();
        } else {
          danmakusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder addDanmakus(bilibilispider.multiprocess.Serialize.Msg.DanmakuP value) {
        if (danmakusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDanmakusIsMutable();
          danmakus_.add(value);
          onChanged();
        } else {
          danmakusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder addDanmakus(
          int index, bilibilispider.multiprocess.Serialize.Msg.DanmakuP value) {
        if (danmakusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDanmakusIsMutable();
          danmakus_.add(index, value);
          onChanged();
        } else {
          danmakusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder addDanmakus(
          bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder builderForValue) {
        if (danmakusBuilder_ == null) {
          ensureDanmakusIsMutable();
          danmakus_.add(builderForValue.build());
          onChanged();
        } else {
          danmakusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder addDanmakus(
          int index, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder builderForValue) {
        if (danmakusBuilder_ == null) {
          ensureDanmakusIsMutable();
          danmakus_.add(index, builderForValue.build());
          onChanged();
        } else {
          danmakusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder addAllDanmakus(
          java.lang.Iterable<? extends bilibilispider.multiprocess.Serialize.Msg.DanmakuP> values) {
        if (danmakusBuilder_ == null) {
          ensureDanmakusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, danmakus_);
          onChanged();
        } else {
          danmakusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder clearDanmakus() {
        if (danmakusBuilder_ == null) {
          danmakus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          danmakusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public Builder removeDanmakus(int index) {
        if (danmakusBuilder_ == null) {
          ensureDanmakusIsMutable();
          danmakus_.remove(index);
          onChanged();
        } else {
          danmakusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder getDanmakusBuilder(
          int index) {
        return getDanmakusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder getDanmakusOrBuilder(
          int index) {
        if (danmakusBuilder_ == null) {
          return danmakus_.get(index);  } else {
          return danmakusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public java.util.List<? extends bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder> 
           getDanmakusOrBuilderList() {
        if (danmakusBuilder_ != null) {
          return danmakusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(danmakus_);
        }
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder addDanmakusBuilder() {
        return getDanmakusFieldBuilder().addBuilder(
            bilibilispider.multiprocess.Serialize.Msg.DanmakuP.getDefaultInstance());
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder addDanmakusBuilder(
          int index) {
        return getDanmakusFieldBuilder().addBuilder(
            index, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.getDefaultInstance());
      }
      /**
       * <code>repeated .bilibilispider.multiprocess.Msg.DanmakuP danmakus = 1;</code>
       */
      public java.util.List<bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder> 
           getDanmakusBuilderList() {
        return getDanmakusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          bilibilispider.multiprocess.Serialize.Msg.DanmakuP, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder, bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder> 
          getDanmakusFieldBuilder() {
        if (danmakusBuilder_ == null) {
          danmakusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              bilibilispider.multiprocess.Serialize.Msg.DanmakuP, bilibilispider.multiprocess.Serialize.Msg.DanmakuP.Builder, bilibilispider.multiprocess.Serialize.Msg.DanmakuPOrBuilder>(
                  danmakus_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          danmakus_ = null;
        }
        return danmakusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bilibilispider.multiprocess.Msg)
    }

    // @@protoc_insertion_point(class_scope:bilibilispider.multiprocess.Msg)
    private static final bilibilispider.multiprocess.Serialize.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bilibilispider.multiprocess.Serialize.Msg();
    }

    public static bilibilispider.multiprocess.Serialize.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bilibilispider.multiprocess.Serialize.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibilispider_multiprocess_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibilispider_multiprocess_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bilibilispider_multiprocess_Msg_DanmakuP_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bilibilispider_multiprocess_Msg_DanmakuP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Serialize.proto\022\033bilibilispider.multip" +
      "rocess\"\376\001\n\003Msg\022;\n\010danmakus\030\001 \003(\0132).bilib" +
      "ilispider.multiprocess.Msg.DanmakuP\032\271\001\n\010" +
      "DanmakuP\022\n\n\002id\030\001 \001(\003\022\014\n\004mode\030\002 \001(\005\022\020\n\010fo" +
      "ntSize\030\003 \001(\005\022\021\n\tfontColor\030\004 \001(\005\022\020\n\010sendT" +
      "ime\030\005 \001(\003\022\023\n\013danmakuPool\030\006 \001(\005\022\024\n\014danmak" +
      "uEpoch\030\010 \001(\001\022\020\n\010userHash\030\t \001(\003\022\016\n\006userId" +
      "\030\n \001(\003\022\017\n\007content\030\013 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bilibilispider_multiprocess_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bilibilispider_multiprocess_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibilispider_multiprocess_Msg_descriptor,
        new java.lang.String[] { "Danmakus", });
    internal_static_bilibilispider_multiprocess_Msg_DanmakuP_descriptor =
      internal_static_bilibilispider_multiprocess_Msg_descriptor.getNestedTypes().get(0);
    internal_static_bilibilispider_multiprocess_Msg_DanmakuP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bilibilispider_multiprocess_Msg_DanmakuP_descriptor,
        new java.lang.String[] { "Id", "Mode", "FontSize", "FontColor", "SendTime", "DanmakuPool", "DanmakuEpoch", "UserHash", "UserId", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
